### ISSUE TITLE
When using OAuth stuff breaks for no reason

### ISSUE THREAD

**Issue by chuggafan** [chuggafan/Mnemosyne-2.0#8]
401 web request when using OAuth, works fine otherwise @Spootacular

**Comment by Spootacular** [comment]
Did it happen to occur after an hour or so?

**Comment by chuggafan** [comment]
nope, immediately, webexcetion that was being thrown at entirely the wrong location, fixed when i stopped using OAuth

**Comment by Spootacular** [comment]
I thought maybe it did need to refresh its token, but as far as I can find 401 is sent for incorrect credentials.

**Comment by chuggafan** [comment]
hmmmmmm then i may need to retry, brb

**Comment by chuggafan** [comment]
Yhea, i was being stupid with OAuth, will close this now
